---
version: 2

updates:
  - commit-message:
      prefix: deps
      prefix-development: chore(dev-deps)
    directory: /
    open-pull-requests-limit: 10
    package-ecosystem: pip
    reviewers: [bryant-finney]
    rebase-strategy: auto
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
